#
#
obj-$(CONFIG_MACH_ABILENE) += lcd_mipi.o
obj-$(CONFIG_MACH_YELLOWSTONE) += lcd_mipi.o
obj-$(CONFIG_UIO_HDMI) += lcd_hdmi.o
obj-$(CONFIG_MACH_TTC_DKB) += lcd_tpo.o lcd_truly.o lcd_sharp.o
obj-$(CONFIG_MACH_BROWNSTONE) += lcd_mipi.o
