#!/bin/sh

mount -t devtmpfs nodev /dev
mkdir /dev/pts
mount -t devpts nodev /dev/pts
mount -t proc nodev /proc
mount -t sysfs nodev /sys
mount -t debugfs node /sys/kernel/debug
ip link set eth0 up
telnetd -l sh
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

#echo mmc1:0001:1 >/sys/bus/sdio/drivers/libertas_sdio/unbind
#echo mmc1:0001:1 >/sys/bus/sdio/drivers/libertas_sdio/bind
