#!/bin/sh

mount -t devtmpfs nodev /dev
mount -t proc nodev /proc
mount -t sysfs nodev /sys
mount -t debugfs node /sys/kernel/debug

#echo mmc1:0001:1 >/sys/bus/sdio/drivers/libertas_sdio/unbind
#echo mmc1:0001:1 >/sys/bus/sdio/drivers/libertas_sdio/bind
